import type { Metadata } from "next";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/SessionProvider";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NextAuthSessionProvider>
          <Navbar />
          {children}
        </NextAuthSessionProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
